name: dlibphonenumber
description: This is a Dart port of Google's libphonenumber library, Google's library for parsing, formatting, and validating international phone numbers. 
version: 1.1.31
homepage: https://github.com/superakabo/dlibphonenumber
topics:
  - phonenumber
  - parsing
  - formatting
  - validation
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ^3.0.0

dependencies:
  protobuf: ^3.1.0
  meta: ^1.11.0
  fixnum: ^1.1.0
   
dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.9
  args: ^2.4.2
  xml: ^6.5.0
  yaml_edit: ^2.2.1
